import { Navbar } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        {/* ===== TITLE ===== */}
        <title>NFT Showcase</title>
        {/* ===== META TAGS ===== */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* ===== FAVICON ===== */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex font-poppins bg-background">
        <Navbar />
      </main>
    </>
  );
}
